### ISSUE TITLE
AttributeError: 'Coverage' object has no attribute 'omit_match'

### ISSUE THREAD

**Issue by Levitanus** [perimosocordiae/PyCover#15]
```
PyCover: Traceback (most recent call last):
  File "/home/levitanus/.config/sublime-text-3/Packages/PyCover/scripts/missing_lines.py", line 17, in <module>
    missing_lines(*sys.argv[1:])
  File "/home/levitanus/.config/sublime-text-3/Packages/PyCover/scripts/missing_lines.py", line 9, in missing_lines
    if cov.omit_match and cov.omit_match.match(fname):
AttributeError: 'Coverage' object has no attribute 'omit_match'
```

Ubuntu 19.10, python 3.7.5, Coverage.py version 5.0.1 with C extension

**Comment by curlup** [comment]
Any clues?

**Comment by perimosocordiae** [comment]
gh-16 implemented a fix for this issue, as far as I'm aware, but I haven't gotten around to releasing a new version yet. I'll do that now.

**Comment by perimosocordiae** [comment]
Ok, the new release is up, so once Package Control updates please try again.
